Fix missing LBaaS Backend attributes for Create operations
anexia-it/go-anxcloud pull request #135
Opened 2022-04-28 10:56 UTC by LittleFox94

### Description

When creating a Backend, only a certain subset of attributes was sent to the Engine.

Also improves the request body handling for all the LBaaS objects, unifying Create and Update and omitting the State attribute instead of choosing the correct one to send and adds some `omitempty` tags to Object fields.

### Checklist

* [ ] added release notes to `Unreleased` section in [CHANGELOG.md](CHANGELOG.md), if user facing change

### References

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

2022-04-28 12:39 UTC, LittleFox94 commented
I'll merge this myself after approval, maybe I can prevent swamping the queue

2022-04-28 14:44 UTC, marioreggiori requested changes

2022-04-28 14:44 UTC, marioreggiori commented on pkg/apis/lbaas/v1/helper.go
> +		return res, err
return `nil` on error

2022-04-29 08:59 UTC, LittleFox94 commented on pkg/apis/lbaas/v1/helper.go
> +		return res, err
fixed :)

2022-04-29 09:11 UTC, marioreggiori approved these changes
lgtm

2022-05-02 08:06 UTC, toothstone commented
@LittleFox94 Could you have a quick look if this is also already doing https://ats.anexia-it.com/browse/SYSENG-1013 ? AFAIK LBaaS is the only Generic Service wrapped in go-anxcloud so far, and I'm not aware of any other "optional" fields that had to be sent in earlier Engine versions.

2022-05-02 08:11 UTC, LittleFox94 commented
> @LittleFox94 Could you have a quick look if this is also already doing https://ats.anexia-it.com/browse/SYSENG-1013 ? AFAIK LBaaS is the only Generic Service wrapped in go-anxcloud so far, and I'm not aware of any other "optional" fields that had to be sent in earlier Engine versions.

one of the functional changes of this PR is to not send the `state` attribute in request bodies anymore, which probably matches SYSENG-1013. We also do not send some empty fields anymore, but that's probably another thing.

2022-05-03 06:26 UTC, marioreggiori commented on pkg/apis/lbaas/v1/loadbalancer_types.go
> +// anxcloud:object:hooks=RequestBodyHook,ResponseFilterHook
Are these hooks correkt? I can only find `FilterAPIResponse` on `commonMethods`.

2022-05-03 06:29 UTC, marioreggiori commented on pkg/apis/lbaas/v1/loadbalancer_types.go
> +// anxcloud:object:hooks=RequestBodyHook,ResponseFilterHook
NVM.. found them

2022-05-03 06:33 UTC, marioreggiori commented
lgtm

2022-05-03 07:35 UTC, merged