Upgrade to go 1.16 and document target version
anexia-it/go-anxcloud pull request #95
Opened 2021-12-09 14:15 UTC by LittleFox94

### Description

This changes the minimum Go version of this package to 1.16, the minimal currently supported version of Go, and adds documentation how we are going to lift the minimum Go version required by this package.

Also changes the GitHub actions workflows to matrix-test two Go versions, currently 1.16 and 1.17.

### Release Note
Release note for [CHANGELOG](https://github.com/anexia-it/go-anxcloud/blob/master/CHANGELOG.md):

```release-note
* now requiring at least Go 1.16
```

### References

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

2021-12-09 15:32 UTC, toothstone requested changes

2021-12-09 15:32 UTC, toothstone commented on docs/go-versions.md
> +We follow Go's release policy, meaning we target it's latest minor version and the minor version before
*its

2021-12-09 15:51 UTC, LittleFox94 commented on docs/go-versions.md
> +We follow Go's release policy, meaning we target it's latest minor version and the minor version before
oh, right

2021-12-10 09:00 UTC, toothstone approved these changes

2021-12-10 09:01 UTC, merged